=== vtertre/Carpooling-ContractFirst-WS/src/main/resources/VicinityRequest.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:hr="http://iaws/ws/contractfirst/covoiturage" elementFormDefault="qualified"
	targetNamespace="http://iaws/ws/contractfirst/covoiturage">

	<xs:element name="VicinityRequest" type="exem:VicinityRequestType"
		xmlns:exem="http://iaws/ws/contractfirst/covoiturage" />

	<xs:complexType name="VicinityRequestType">
		<xs:all>
			<xs:element type="xs:string" name="Identifiant" />
			<xs:element type="xs:string" name="Rayon" />
		</xs:all>
	</xs:complexType>


	<xs:element name="VicinityDetails" type="exem:VicinityDetailsType"
		xmlns:exem="http://iaws/ws/contractfirst/covoiturage" />

	<xs:complexType name="VicinityDetailsType">
		<xs:sequence>
			<xs:element type="exem:PersonnelType" name="Personnel"
				maxOccurs="unbounded" minOccurs="0"
				xmlns:exem="http://iaws/ws/contractfirst/covoiturage" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PersonnelType">
		<xs:all>
			<xs:element type="exem:IdentiteType" name="Identite"
				maxOccurs="1" minOccurs="1" xmlns:exem="http://iaws/ws/contractfirst/covoiturage" />
			<xs:element type="exem:MailType" name="Mail" maxOccurs="1"
				minOccurs="1" xmlns:exem="http://iaws/ws/contractfirst/covoiturage" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="IdentiteType">
		<xs:all>
			<xs:element type="xs:string" name="Nom" />
			<xs:element type="xs:string" name="Prenom" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="MailType">
		<xs:all>
			<xs:element type="xs:string" name="Perso" />
			<xs:element type="xs:string" name="Domaine" />
		</xs:all>
	</xs:complexType>

</xs:schema>

=== vtertre/Carpooling-ContractFirst-WS/src/main/resources/VicinityDetails.xml
<VicinityDetails xmlns="http://iaws/ws/contractfirst/covoiturage"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://iaws/ws/contractfirst/covoiturage VicinityRequest.xsd">
	
	<Personnel>
		<Identite>
			<Nom>LastName</Nom>
			<Prenom>FirstName</Prenom>
		</Identite>
		<Mail>
			<Perso>firstname.lastname</Perso>
			<Domaine>univ-tlse3.fr</Domaine>
		</Mail>
	</Personnel>
	
	<Personnel>
		<Identite>
			<Nom>Bob</Nom>
			<Prenom>Gaston</Prenom>
		</Identite>
		<Mail>
			<Perso>gaston.bob</Perso>
			<Domaine>univ-tlse3.fr</Domaine>
		</Mail>
	</Personnel>
	
</VicinityDetails>
