=== vtertre/Carpooling-ContractFirst-WS/Carpooling-WS/src/main/webapp/WEB-INF/xsd/InscriptionRequest.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cov="http://iaws/ws/contractfirst/carpooling" elementFormDefault="qualified"
	targetNamespace="http://iaws/ws/contractfirst/carpooling">
	
	<xs:element name="InscriptionRequest">
		<xs:complexType>
			<xs:all>
				<xs:element name="Id" type="cov:IdType" />
				<xs:element name="Mail" type="cov:MailType" />
				<xs:element name="MailingAddress" type="cov:MailingAddressType" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="IdType">
		<xs:sequence>
			<xs:element name="Lastname" type="xs:string" />
			<xs:element name="Firstname" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="MailType">
		<xs:sequence>
			<xs:element name="Perso" type="xs:string" />
			<xs:element name="Domain" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="MailingAddressType">
		<xs:sequence>
			<xs:element name="Street" type="xs:string" />
			<xs:element name="Code" type="xs:string" />
			<xs:element name="City" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="InscriptionDetails">
		<xs:complexType>
			<xs:all>
				<xs:element name="Operation" type="xs:string" />
				<xs:element name="Code" type="xs:string" />
				<xs:element name="Message" type="xs:string" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== vtertre/Carpooling-ContractFirst-WS/Carpooling-WS/src/main/resources/InscriptionRequest.xml
<InscriptionRequest xmlns="http://iaws/ws/contractfirst/carpooling" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://iaws/ws/contractfirst/carpooling InscriptionRequest.xsd">
	<Id>
		<Lastname>Totoé</Lastname>
		<Firstname>TotoAussi</Firstname>
	</Id>
	<Mail>
		<Perso>toto</Perso>
		<Domain>univ-tlse3.fr</Domain>
	</Mail>
	<MailingAddress>
		<Street>Université Paul Sabatier</Street>
		<Code>31000</Code>
		<City>Toulouse</City>
	</MailingAddress>
</InscriptionRequest>
