=== vtertre/Carpooling-ContractFirst-WS/Carpooling-WS/src/main/webapp/WEB-INF/xsd/VicinityRequest.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cov="http://iaws/ws/contractfirst/carpooling" elementFormDefault="qualified"
	targetNamespace="http://iaws/ws/contractfirst/carpooling">
	
	<xs:element name="VicinityRequest">
		<xs:complexType>
			<xs:all>
				<xs:element name="Id" type="xs:string" />
				<xs:element name="Radius" type="xs:short" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="VicinityDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Teacher" type="cov:TeacherType" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="TeacherType">
		<xs:all>
			<xs:element name="Id" type="cov:IdType" />
			<xs:element name="Mail" type="cov:MailType" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="IdType">
		<xs:all>
			<xs:element name="Lastname" type="xs:string" />
			<xs:element name="Firstname" type="xs:string" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="MailType">
		<xs:all>
			<xs:element name="Perso" type="xs:string" />
			<xs:element name="Domain" type="xs:string" />
		</xs:all>
	</xs:complexType>
	
</xs:schema>

=== vtertre/Carpooling-ContractFirst-WS/Carpooling-WS/src/main/resources/VicinityDetails.xml
<VicinityDetails xmlns="http://iaws/ws/contractfirst/carpooling"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://iaws/ws/contractfirst/carpooling VicinityRequest.xsd">
	
	<Teacher>
		<Id>
			<Lastname>Lastname</Lastname>
			<Firstname>Firstname</Firstname>
		</Id>
		<Mail>
			<Perso>firstname.lastname</Perso>
			<Domain>univ-tlse3.fr</Domain>
		</Mail>
	</Teacher>
	
	<Teacher>
		<Id>
			<Lastname>Nom</Lastname>
			<Firstname>Pr√©nom</Firstname>
		</Id>
		<Mail>
			<Perso>prenom.nom</Perso>
			<Domain>univ-tlse3.fr</Domain>
		</Mail>
	</Teacher>
	
</VicinityDetails>
